algoritmo "semnome"
var
x,opcao:inteiro
inicio
 repita
   escreval("1- Dizer Olá")
   escreval("2- Dizer Oi!")
   escreval("3- Sair do programa")
   leia(opcao)
   LimpaTela
   se(opcao=1)entao
     escreval("Olá")
   fimse
   se(opcao=2)entao
     escreval("Oi")
   fimse
 ate(opcao=3)
fimalgoritmo




========================NADA A VER COM O ASSUNTO=====================================================
//Feijão R$7,28,Arroz R$5,14,Carne sem osso R$18,36, Calabresa R$ 9,98