algoritmo "Sem NOME"
var
A,B,C,soma:inteiro
inicio
      escreva("Insira primeiro numero: ")
      leia(A)
      escreva("Insira segundo numero: ")
      leia(B)
      escreva("Insira terceiro numero: ")
      leia(C)
      soma <- A + B
      
      Se soma < C entao
         escrevaL("A soma de", A," +", B," é menor que",C)
      senao
         escreval("A soma de", A," +", B," é maior que",C)
      fimse
fimalgoritmo